### ISSUE TITLE
Setup workspace cho backend + frontend. install dependencies

### ISSUE THREAD

**Issue by Aikadev27** [LV-DinhHoangNhan-B2007253/GraduationThesis#1]
create work environment for front-end using NextJs ( setup routes, axios, css lib, icon lib, component, interfaces, theme, font, variable, modulize call api service, create store for global states). Setup NestJS for backend, create sample module and services, provider, CORS. Setup init Firesbase and Firestore.

**Comment by AikaDreamer** [comment]
done
