### ISSUE TITLE
Viết API cho chức năng liên quan đến Auth như đăng nhập, đăng ký tích hợp với  OAuth2.0 liên kết mạng xã hội

### ISSUE THREAD

**Issue by Aikadev27** [LV-DinhHoangNhan-B2007253/GraduationThesis#9]

**Comment by AikaDreamer** [comment]
![image](https://github.com/user-attachments/assets/f788c470-ff58-4d63-9aad-169fb3d8eef2)
- nếu  đăng nhập lần đầu bằng gg email  -> tạo user data và lưu vào db
-  nếu đã đăng nhập -> login -> trả về data cho client xử lí
